webface: fw cleanups
git-svn-id: http://midge.vlad.org.ua/svn/trunk@170 9f4ba3df-1318-0410-9984-8b9d03078064

diff --git a/openwrt-midge/target/linux/package/base-files/files/adm5120-2.6/etc/init.d/autoreboothack b/openwrt-midge/target/linux/package/base-files/files/adm5120-2.6/etc/init.d/autoreboothack
--- a/openwrt-midge/target/linux/package/base-files/files/adm5120-2.6/etc/init.d/autoreboothack
+++ b/openwrt-midge/target/linux/package/base-files/files/adm5120-2.6/etc/init.d/autoreboothack
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-echo test >/test && echo "No autoreboot hack" || ( echo "Autoreboot hack: Cannot write to rootfs - rebooting"; sleep 1; reboot -f; sleep 5; halt -f )
+echo test >/test || ( echo "Autoreboot hack: Cannot write to rootfs - rebooting"; sleep 3; reboot -f; sleep 5; halt -f )
 
 [ -f /test ] && rm /test
 
